### ISSUE TITLE
Only show published organisms 

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/t3_species_glossary#2]
Looks like it currently counts all organisms, not just published ones: 
![Screen Shot 2020-07-10 at 2 18 34 PM](https://user-images.githubusercontent.com/5487172/87199240-4542d400-c2b8-11ea-8db9-1402d23c7492.png)

**Comment by Ferrisx4** [comment]
This is the default functionality. The site in question was showing every organism in the database because they were all 'published'. Unpublishing an organism removes it from this list immediately.
