### ISSUE TITLE
Remove 'Tripal 3' from title and description before prod push

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/t3_species_glossary#3]
having the title and description specify Tripal 3 is nice for development and debugging - adding this issue so that we remember to delete the Tripal 3 part before moving this to production

**Comment by Ferrisx4** [comment]
Fixed with https://github.com/NAL-i5K/t3_species_glossary/commit/56dd144ce09a6b69fc63d4c12f0e87e9bec0272d
